[package]
name = "slimevr-wrangler"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
iced = { version = "0.3", features = ["async-std", "svg", "wgpu"] }
iced_native = "0.4"
async-std = "1.0"
joycon-rs = { version = "0.6", optional = true }
joycon = { git = "https://github.com/Yamakaky/joy", optional = true }
directories = "4.0"
self_update = { version = "0.27", features = ["archive-zip", "compression-zip-deflate"] }
itertools = "0.10"
ahrs = "0.4"
nalgebra = "0.21"
deku = "0.12"
md-5 = "0.9"

[features]
default = ["use-joycon-rs"]
use-joycon-rs = ["joycon-rs"]
use-joy = ["joycon"]

[profile.release]
lto = true
codegen-units = 1
# panic = "abort" # Doesn't allow threads to catch themselves
opt-level = "s"